name: Welcome

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
              🚀 Thank you for joining to the UESTC Community! 🚀

              Before merging, please ensure to follow the process below:

              1. Make sure you have created an issue for your application
              2. Make sure you have created a PR for adding your github ID

          reactions: 'heart'
